// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NxfQmk_zhTUGhhUwV3TWCr8AaOkgId8',
    appId: '1:746385504918:web:fe61a87edc2360002ba0b7',
    messagingSenderId: '746385504918',
    projectId: 'farmereats-a0ccc',
    authDomain: 'farmereats-a0ccc.firebaseapp.com',
    databaseURL: 'https://farmereats-a0ccc-default-rtdb.firebaseio.com',
    storageBucket: 'farmereats-a0ccc.appspot.com',
    measurementId: 'G-E3YG4TJEKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0hb2d7es2Z_X52JZS5ovUbhRIwgbhJQ',
    appId: '1:746385504918:android:f977f71f94d80dfd2ba0b7',
    messagingSenderId: '746385504918',
    projectId: 'farmereats-a0ccc',
    databaseURL: 'https://farmereats-a0ccc-default-rtdb.firebaseio.com',
    storageBucket: 'farmereats-a0ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJE8Zlx5cjfVl_Pcf28E6b9r-mBmgx2as',
    appId: '1:746385504918:ios:0d7fab599e8211062ba0b7',
    messagingSenderId: '746385504918',
    projectId: 'farmereats-a0ccc',
    databaseURL: 'https://farmereats-a0ccc-default-rtdb.firebaseio.com',
    storageBucket: 'farmereats-a0ccc.appspot.com',
    androidClientId: '746385504918-i523gisgpbuhm47jreb2eu8j4mm2pjb8.apps.googleusercontent.com',
    iosClientId: '746385504918-4c3jjgf45qb7jlcske4p463vl256n9nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.famerEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJE8Zlx5cjfVl_Pcf28E6b9r-mBmgx2as',
    appId: '1:746385504918:ios:9f00fd98b85a26cc2ba0b7',
    messagingSenderId: '746385504918',
    projectId: 'farmereats-a0ccc',
    databaseURL: 'https://farmereats-a0ccc-default-rtdb.firebaseio.com',
    storageBucket: 'farmereats-a0ccc.appspot.com',
    androidClientId: '746385504918-i523gisgpbuhm47jreb2eu8j4mm2pjb8.apps.googleusercontent.com',
    iosClientId: '746385504918-8dlsgsvb91tem8l7pj5lb1nra3nv7ha2.apps.googleusercontent.com',
    iosBundleId: 'com.example.famerEats.RunnerTests',
  );
}
